
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/jpaupasana?createDatabaseIfNotExist=true
    username: root
    password: root
 